# Generated by Django 5.0.3 on 2024-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_cate',
            name='cate_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
