# Generated by Django 5.0.3 on 2024-04-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_menu_cate_cate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
                ('ordered_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.menu')),
            ],
        ),
    ]
